# Generated by Django 3.2 on 2021-05-01 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MasterEntry', '0004_auto_20210501_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=20)),
                ('hospital_contact', models.EmailField(max_length=254)),
                ('hospital_proof', models.FileField(upload_to='HospitalProof/')),
                ('hospital_image', models.ImageField(upload_to='HospitalImage/')),
                ('hospital_status', models.IntegerField(default=0)),
                ('hospital_doj', models.DateField(auto_now_add=True)),
                ('hospital_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterEntry.place')),
                ('hospital_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterEntry.hospitaltype')),
            ],
        ),
    ]
