# Generated by Django 3.2 on 2021-05-01 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterEntry', '0004_auto_20210501_1536'),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='hospital_email',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_password',
            field=models.CharField(default=True, max_length=15),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_username',
            field=models.CharField(default=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='hospital_contact',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('user_contact', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_gender', models.CharField(max_length=20)),
                ('user_username', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
                ('user_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterEntry.place')),
            ],
        ),
    ]
