# Generated by Django 3.2.3 on 2021-05-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_hospital_hospital_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_contact',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_email',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_gender',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_name',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_password',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_place',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='user_username',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
