# Generated by Django 3.2 on 2021-05-01 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterEntry', '0003_auto_20210501_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainttype',
            name='complainttype_name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabetic characters are allowed.')], verbose_name='Complaint Type'),
        ),
        migrations.AlterField(
            model_name='district',
            name='district_name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabetic characters are allowed.')], verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='hospitaltype',
            name='hospitaltype_name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabetic characters are allowed.')], verbose_name='Hospital Type'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_name',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabetic characters are allowed.')], verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='servicedesignation',
            name='service_designation',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabetic characters are allowed.')], verbose_name='Service Designation'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='servicetype_name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z ]*$', 'Only alphabetic characters are allowed.')], verbose_name='Service Type'),
        ),
    ]
